# Generated by Django 4.1 on 2022-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_productfeature_delete_feature_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="color",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ManyToManyField(to="shop.color"),
        ),
    ]
